// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMVyTppPG-Cl9eywZI9GgcTe4G5TbaQcE',
    appId: '1:1089509269321:web:83562c7aeb1120b2bb4498',
    messagingSenderId: '1089509269321',
    projectId: 'chatapp-7ff8f',
    authDomain: 'chatapp-7ff8f.firebaseapp.com',
    storageBucket: 'chatapp-7ff8f.appspot.com',
    measurementId: 'G-H44TQYJDP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHaOmZKg4uu3bMYa_gi0i3Yuao1vId38Q',
    appId: '1:1089509269321:android:6b80c97480fb2163bb4498',
    messagingSenderId: '1089509269321',
    projectId: 'chatapp-7ff8f',
    storageBucket: 'chatapp-7ff8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXjTuFwUF0rhk7eU-1hyfv3RLcpvI-Oog',
    appId: '1:1089509269321:ios:814d65e6cd755f2ebb4498',
    messagingSenderId: '1089509269321',
    projectId: 'chatapp-7ff8f',
    storageBucket: 'chatapp-7ff8f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXjTuFwUF0rhk7eU-1hyfv3RLcpvI-Oog',
    appId: '1:1089509269321:ios:07e5ad04eb12c82cbb4498',
    messagingSenderId: '1089509269321',
    projectId: 'chatapp-7ff8f',
    storageBucket: 'chatapp-7ff8f.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
